Cienciometrico/Cienciometrico/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import login, logout_then_login,password_reset,password_reset_done,password_reset_confirm,password_reset_complete
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.principal.urls', namespace="iniciop")),
    url(r'^pais/', include('apps.pais.urls', namespace="pais")),
    url(r'^zona/', include('apps.zona.urls', namespace="zona")),
    url(r'^provincia/', include('apps.provincia.urls', namespace="provincia")),
    url(r'^canton/', include('apps.canton.urls', namespace="canton")),
    url(r'^universidad/', include('apps.universidad.urls', namespace="universidad")),
    url(r'^Carrera/', include('apps.carrera.urls', namespace="carrera")),
    url(r'^Facultad/', include('apps.facultad.urls', namespace="Facultad")),
    url(r'^campus/', include('apps.campus.urls', namespace="campus")),
    url(r'^investigador/', include('apps.Investigador.urls', namespace="investigador")),
    url(r'^articulo/', include('apps.Articulos_Cientificos.urls', namespace="articulosCientificos")),
    url(r'^investigacion/', include('apps.investigaciones.urls', namespace="investigacion")),
    url(r'^datosprofesionales/', include('apps.datosprofesionales.urls', namespace="datosprofe")),
    url(r'^formacionAcad/', include('apps.Formacion_Academica.urls', namespace="FormacionAcademica")),
    url(r'^formacionComple/', include('apps.Formacion_Complementaria.urls', namespace="FormacionComplementaria")),
    url(r'^Evento/', include('apps.Evento.urls', namespace="evento")),
    url(r'^otrainvestigacion/', include('apps.otrasinvestigaciones.urls', namespace="otrainvestigacion")),
    url(r'^participacioneventos/', include('apps.participacioneventos.urls', namespace="partevento")),
    url(r'^proyectos/', include('apps.Proyectos.urls', namespace="proyecto")),
    url(r'^perfiles/', include('apps.perfiles.urls', namespace="usuario")),
    url(r'^roles/', include('apps.roles.urls', namespace="roles")),
    url(r'^login/', include('apps.inicio.urls', namespace="inicio")),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^accounts/login', login,{'template_name':'login.html'},name='login'),
    url(r'^logout/', logout_then_login,  name='logout'),
    url(r'^libro/', include('apps.Libro.urls', namespace="Libro")),
    url(r'^revista/', include('apps.Revista.urls', namespace="Revista")),
    url(r'^Publicaciones/', include('apps.Publicaciones.urls', namespace="publicaciones")),
    #///////////////////////PASSWORD RESET///////////////////////////////////////
    url(r'^password_reset/', password_reset,
       {'template_name': 'registration/password_reset_form.html',
   'email_template_name': 'registration/password_reset_email.html'},
     name='password_reset'),
    url(r'^password_reset_done/', password_reset_done,
       {'template_name': 'registration/password_reset_done.html'},
        name='password_reset_listo'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
        {'template_name': 'registration/password_reset_confirm.html'},
        name='password_reset_confirm'
        ),
    url(r'^done', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},
        name='password_reset_completado'),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Cienciometrico/apps/inicio/urls.py
from apps.inicio.views import inicio
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
urlpatterns = [

    url(r'^inicio$',login_required(inicio), name="logeo"),
    ]

Cienciometrico/apps/pais/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from apps.pais.models import pais
from apps.pais.views import PaisCreate, PaisList, PaisUpdate, PaisDelete
from django.contrib.auth.decorators import login_required
urlpatterns = [
    url(r'^nuevo',login_required(PaisCreate.as_view()), name='pais_crear'),
    url(r'^listar',login_required(PaisList.as_view(queryset= pais.objects.all().order_by('id'))), name='pais_listar'),
    url(r'^editar/(?P<pk>\d+)/$',login_required(PaisUpdate.as_view()), name='pais_editar'),
    url(r'^eliminar/(?P<pk>\d+)/$',login_required(PaisDelete.as_view()), name='pais_eliminar'),

]

Cienciometrico/apps/pais/models.py
from django.db import models

# Create your models here.
class pais (models.Model):
    Iso=models.CharField(max_length=2)
    Nombre=models.CharField(max_length=150)

    def __str__(self):
        return '{}'.format(self.Nombre)

    class Meta:
        permissions = (
            ("ver_pais", "ver pais"),
        )

Cienciometrico/apps/pais/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse_lazy
from apps.pais.form import PaisForm
from apps.pais.models import pais
from django.views.generic import ListView, CreateView,UpdateView,DeleteView
from apps.perfiles.models import Perfil
from apps.roles.models import Rol

# Create your views here.
class PaisList(ListView):
    model = pais
    template_name = 'pais/pais_listar.html'
    paginate_by = 6

    def get_context_data(self, **kwargs):
        context = super(PaisList, self).get_context_data(**kwargs)
        usuario = self.request.user.id
        perfil = Perfil.objects.get(user_id=usuario)
        roles = perfil.roles.all()
        privi = []
        privilegios = []
        privilegio = []
        for r in roles:
            privi.append(r.id)
        for p in privi:
            roles5 = Rol.objects.get(pk=p)
            priv = roles5.privilegios.all()
            for pr in priv:
                privilegios.append(pr.codename)
        for i in privilegios:
            if i not in privilegio:
                privilegio.append(i)
        context['usuario'] = privilegio
        return context

class PaisCreate(CreateView):
    model = pais
    form_class = PaisForm
    template_name = 'pais/pais_crear.html'
    success_url = reverse_lazy('pais:pais_listar')
    def get_context_data(self, **kwargs):
        context = super(PaisCreate, self).get_context_data(**kwargs)
        usuario = self.request.user.id
        perfil = Perfil.objects.get(user_id=usuario)
        roles = perfil.roles.all()
        privi = []
        privilegios = []
        privilegio = []
        for r in roles:
            privi.append(r.id)
        for p in privi:
            roles5 = Rol.objects.get(pk=p)
            priv = roles5.privilegios.all()
            for pr in priv:
                privilegios.append(pr.codename)
        for i in privilegios:
            if i not in privilegio:
                privilegio.append(i)
        context['usuario'] = privilegio
        return context
class PaisUpdate(UpdateView):
    model = pais
    form_class = PaisForm
    template_name = 'pais/pais_update.html'
    success_url = reverse_lazy('pais:pais_listar')
    def get_context_data(self, **kwargs):
        context = super(PaisUpdate, self).get_context_data(**kwargs)
        usuario = self.request.user.id
        perfil = Perfil.objects.get(user_id=usuario)
        roles = perfil.roles.all()
        privi = []
        privilegios = []
        privilegio = []
        for r in roles:
            privi.append(r.id)
        for p in privi:
            roles5 = Rol.objects.get(pk=p)
            priv = roles5.privilegios.all()
            for pr in priv:
                privilegios.append(pr.codename)
        for i in privilegios:
            if i not in privilegio:
                privilegio.append(i)
        context['usuario'] = privilegio
        return context
class PaisDelete(DeleteView):
    model = pais
    template_name = 'pais/pais_eliminar.html'
    success_url = reverse_lazy('pais:pais_listar')
    def get_context_data(self, **kwargs):
        context = super(PaisDelete, self).get_context_data(**kwargs)
        usuario = self.request.user.id
        perfil = Perfil.objects.get(user_id=usuario)
        roles = perfil.roles.all()
        privi = []
        privilegios = []
        privilegio = []
        for r in roles:
            privi.append(r.id)
        for p in privi:
            roles5 = Rol.objects.get(pk=p)
            priv = roles5.privilegios.all()
            for pr in priv:
                privilegios.append(pr.codename)
        for i in privilegios:
            if i not in privilegio:
                privilegio.append(i)
        context['usuario'] = privilegio
        return context

Cienciometrico/templates/pais/pais_crear.html
{% extends 'base1/inicio.html' %}
{% load staticfiles %}
{% load material_form %}
{% load widget_tweaks %}

{% block extrastatic %}
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
   <link rel="stylesheet" href="static/css/animate.min.css">
{% endblock %}
 {% block home %}
    <a href="{% url 'inicio:logeo' %}"  class=" w3-bar-item w3-button"><img width="15%" src="{% static 'images/home.png' %}"> Home</a>
    {% endblock %}
    {% block pais %}
	<a href="{% url 'pais:pais_listar' %}" id="uno" class=" w3-bar-item w3-button"><img width="15%" src="{% static 'images/globe.png' %}"> País</a>
	{% endblock %}
{% block content %}

<form method="post">
    {% csrf_token %}
    <div class="wow fadeInUp animated" style="background: #009688; height:20%;  padding: 1cm 3cm 1cm 3cm;" >
     <h4 align="center" style="color:white"><span class="glyphicon glyphicon-plus"></span> NUEVO <span style="color:#FC9C30">PAÍS</span> </h4>
       <h6> <div style="float:right;">
            <strong style="color:white;font-size:100%">Bienvenido/</strong>
            <strong style="color:white;font-size:100%">{{user.username}}/</strong>
            <strong style="color:white;font-size:100%"><a href="{% url 'logout'%}" style="color:white;"><span class="glyphicon glyphicon-log-out"></span>Cerrar Sesión</a></strong>
        </a>
            </div></h6>
        </div>
    <br>
	<div class="container">
		<div class="col-md-10 col-md-offset-2">
	<a href="{% url 'pais:pais_listar' %}" class="btn btn-primary  pull-right"><i class="glyphicon glyphicon-eye-open"></i> Ver Todos</a>
		</div>
		</div>
    <div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				{% form form=form %}{% endform %}
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<button class="btn btn-primary "type="submit"><span class="glyphicon glyphicon-floppy-disk"></span> Guardar</button>
			</div>
		</div>
	</div>

</form>
{% endblock %}

Cienciometrico/templates/pais/pais_eliminar.html
{% extends 'base1/inicio.html' %}
{% load staticfiles %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <h4>¿Desea eliminar el registro de {{object.Nombre}}?</h4>
    <button class="btn btn-danger" type="submit">Si, eliminar</button>
    <a class="btn btn-default" href="{% url 'pais:pais_listar' %}">Cancelar</a>
</form>
{% endblock %}

Cienciometrico/templates/pais/pais_listar.html
{% extends 'base1/inicio.html' %}
{% load staticfiles %}
{% block extrastatic %}
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
   <link rel="stylesheet" href="static/css/animate.min.css">
{% endblock %}
    {% block home %}
    <a href="{% url 'inicio:logeo' %}"  class=" w3-bar-item w3-button"><img width="15%" src="{% static 'images/home.png' %}"> Home</a>
    {% endblock %}
    {% block pais %}
	<a href="{% url 'pais:pais_listar' %}" id="uno" class=" w3-bar-item w3-button"><img width="15%" src="{% static 'images/globe.png' %}"> País</a>
	{% endblock %}
{% block content %}

<div class="wow fadeInUp animated "  style=" background: #009688; height:20%;  padding: 1cm 3cm 1cm 3cm;" >
     <h4 align="center" style="color:white"><span class="glyphicon glyphicon-plus"></span> LISTADO DE <span style="color:#FC9C30">PAÍSES</span> </h4>
 <h6><div style="float:right;">
            <strong style="color:white;font-size:100%">Bienvenido/</strong>
            <strong style="color:white;font-size:100%">{{user.username}}/</strong>
            <strong style="color:white;font-size:100%"><a href="{% url 'logout'%}" style="color:white;"><span class="glyphicon glyphicon-log-out"></span>Cerrar Sesión</a></strong>
        </a>
            </div></h6>
</div>
    <br>
<div class="container" style="width:90%;">
<a href="{% url 'pais:pais_crear' %}" class="btn btn-primary  pull-right "><i class="glyphicon glyphicon-plus"></i> Nuevo País</a>
    </div>
<br>
<div class="table-responsive">
<table class="table table-bordered" style="text-align:center; width:100%;">
    <thead>
		<tr>
			<td>#</td>
            <td>Iso</td>
			<td>Nombre</td>
			<td>Acciones</td>
		</tr>

	</thead>
	<tbody>
        {% if object_list %}
        {% for pais in object_list %}
        <tr>
            <td>{{pais.id}}</td>
            <td>{{pais.Iso}}</td>
            <td>{{pais.Nombre}}</td>
            <td>
                <a class="btn btn-warning" href="{% url 'pais:pais_editar' pais.id %}"><span class="glyphicon glyphicon-pencil"></span> Editar</a>
                <a class="btn btn-danger" href="{% url 'pais:pais_eliminar' pais.id %}"><span class="glyphicon glyphicon-trash"></span> Eliminar</a>
            </td>
        </tr>
        {% endfor %}

        {% else %}
        <h1 align="center">No hay registros de Países</h1>
        {% endif %}

	</tbody>
</table>
    </div>
<ul class="pager">
    <li>
        {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}
    </li>
    <li>
        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">Next</a>
        {% endif %}
    </li>
</ul>

{% endblock%}

Cienciometrico/templates/pais/pais_update.html
{% extends 'base1/inicio.html' %}
{% load staticfiles %}
{% block extrastatic %}
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
   <link rel="stylesheet" href="static/css/animate.min.css">
{% endblock %}
 {% block home %}
    <a href="{% url 'inicio:logeo' %}"  class=" w3-bar-item w3-button"><img width="15%" src="{% static 'images/home.png' %}"> Home</a>
    {% endblock %}
    {% block pais %}
	<a href="{% url 'pais:pais_listar' %}" id="uno" class=" w3-bar-item w3-button"><img width="15%" src="{% static 'images/globe.png' %}"> País</a>
	{% endblock %}
{% block content %}

<form method="post">
    {% csrf_token %}
    <div class="wow fadeInUp animated" style="background: #009688; height:20%;  padding: 1cm 3cm 1cm 3cm;" >
     <h4 align="center" style="color:white"><span class="glyphicon glyphicon-plus"></span> ACTUALIZAR <span style="color:#FC9C30">PAÍS</span> </h4>
    <h6> <div style="float:right;">
            <strong style="color:white;font-size:100%">Bienvenido/</strong>
            <strong style="color:white;font-size:100%">{{user.username}}/</strong>
            <strong style="color:white;font-size:100%"><a href="{% url 'logout'%}" style="color:white;"><span class="glyphicon glyphicon-log-out"></span>Cerrar Sesión</a></strong>
        </a>
            </div></h6>
	</div>
    <br>
	<div class="container">
		<div class="col-md-10 col-md-offset-2">
	<a href="{% url 'pais:pais_listar' %}" class="btn btn-primary  pull-right"><i class="glyphicon glyphicon-eye-open"></i> Ver Todos</a>
		</div>
		</div>
    <div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label>Iso</label>
				<input class="form-control" type="text" name="Iso" value="{{pais.Iso}}">
			</div>
		</div>
	</div>
    <div class="row" >
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label>Nombre</label>
				<input class="form-control" type="text" name="Nombre" value="{{pais.Nombre}}">
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<button class="btn btn-primary "type="submit"><span class="glyphicon glyphicon-floppy-disk"></span> Guardar</button>
			</div>
		</div>
	</div>

</form>
{% endblock %}