Cienciometrico/Cienciometrico/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import login, logout_then_login,password_reset,password_reset_done,password_reset_confirm,password_reset_complete
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.principal.urls', namespace="iniciop")),
    url(r'^pais/', include('apps.pais.urls', namespace="pais")),
    url(r'^zona/', include('apps.zona.urls', namespace="zona")),
    url(r'^provincia/', include('apps.provincia.urls', namespace="provincia")),
    url(r'^canton/', include('apps.canton.urls', namespace="canton")),
    url(r'^universidad/', include('apps.universidad.urls', namespace="universidad")),
    url(r'^Carrera/', include('apps.carrera.urls', namespace="carrera")),
    url(r'^Facultad/', include('apps.facultad.urls', namespace="Facultad")),
    url(r'^campus/', include('apps.campus.urls', namespace="campus")),
    url(r'^investigador/', include('apps.Investigador.urls', namespace="investigador")),
    url(r'^articulo/', include('apps.Articulos_Cientificos.urls', namespace="articulosCientificos")),
    url(r'^investigacion/', include('apps.investigaciones.urls', namespace="investigacion")),
    url(r'^datosprofesionales/', include('apps.datosprofesionales.urls', namespace="datosprofe")),
    url(r'^formacionAcad/', include('apps.Formacion_Academica.urls', namespace="FormacionAcademica")),
    url(r'^formacionComple/', include('apps.Formacion_Complementaria.urls', namespace="FormacionComplementaria")),
    url(r'^Evento/', include('apps.Evento.urls', namespace="evento")),
    url(r'^otrainvestigacion/', include('apps.otrasinvestigaciones.urls', namespace="otrainvestigacion")),
    url(r'^participacioneventos/', include('apps.participacioneventos.urls', namespace="partevento")),
    url(r'^proyectos/', include('apps.Proyectos.urls', namespace="proyecto")),
    url(r'^perfiles/', include('apps.perfiles.urls', namespace="usuario")),
    url(r'^roles/', include('apps.roles.urls', namespace="roles")),
    url(r'^login/', include('apps.inicio.urls', namespace="inicio")),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^accounts/login', login,{'template_name':'login.html'},name='login'),
    url(r'^logout/', logout_then_login,  name='logout'),
    url(r'^libro/', include('apps.Libro.urls', namespace="Libro")),
    url(r'^revista/', include('apps.Revista.urls', namespace="Revista")),
    url(r'^Publicaciones/', include('apps.Publicaciones.urls', namespace="publicaciones")),
    #///////////////////////PASSWORD RESET///////////////////////////////////////
    url(r'^password_reset/', password_reset,
       {'template_name': 'registration/password_reset_form.html',
   'email_template_name': 'registration/password_reset_email.html'},
     name='password_reset'),
    url(r'^password_reset_done/', password_reset_done,
       {'template_name': 'registration/password_reset_done.html'},
        name='password_reset_listo'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
        {'template_name': 'registration/password_reset_confirm.html'},
        name='password_reset_confirm'
        ),
    url(r'^done', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},
        name='password_reset_completado'),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Cienciometrico/apps/Libro/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from apps.Libro.models import libro
from apps.Libro.views import Librocrear,LibroList,LibroEdit,LibroDelete
from django.contrib.auth.decorators import login_required


urlpatterns = [
    url(r'^uploads/form/$', login_required(Librocrear), name='libro_crear'),
    url(r'^listar', login_required(LibroList.as_view(queryset= libro.objects.all().order_by('id'))), name='libro_lis'),
    url(r'^editar/(?P<id_libro>\d+)/$', login_required(LibroEdit), name='libro_update'),
    url(r'^eliminar/(?P<pk>\d+)/$', login_required(LibroDelete.as_view()), name='libro_eliminar'),

]

Cienciometrico/apps/inicio/urls.py
from apps.inicio.views import inicio
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
urlpatterns = [

    url(r'^inicio$',login_required(inicio), name="logeo"),
    ]

Cienciometrico/apps/pais/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from apps.pais.models import pais
from apps.pais.views import PaisCreate, PaisList, PaisUpdate, PaisDelete
from django.contrib.auth.decorators import login_required
urlpatterns = [
    url(r'^nuevo',login_required(PaisCreate.as_view()), name='pais_crear'),
    url(r'^listar',login_required(PaisList.as_view(queryset= pais.objects.all().order_by('id'))), name='pais_listar'),
    url(r'^editar/(?P<pk>\d+)/$',login_required(PaisUpdate.as_view()), name='pais_editar'),
    url(r'^eliminar/(?P<pk>\d+)/$',login_required(PaisDelete.as_view()), name='pais_eliminar'),

]

Cienciometrico/apps/roles/urls.py
from django.conf.urls import url,include
from apps.roles.views import RegistroRol
urlpatterns = [
    url(r'^nuevo$',RegistroRol.as_view(),name="crear_rol"),


]

Cienciometrico/apps/zona/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from apps.zona.models import zona
from apps.zona.views import ZonaCreate,ZonaList,ZonaDelete,ZonaUpdate
from django.contrib.auth.decorators import login_required
urlpatterns = [
    url(r'^nuevo',login_required(ZonaCreate.as_view()), name='zona_crear'),
    url(r'^listar',login_required(ZonaList.as_view(queryset= zona.objects.all().order_by('id'))), name='zona_listar'),
    url(r'^editar/(?P<pk>\d+)/$',login_required(ZonaUpdate.as_view()), name='zona_editar'),
    url(r'^eliminar/(?P<pk>\d+)/$',login_required(ZonaDelete.as_view()), name='zona_eliminar'),
]

Cienciometrico/apps/inicio/views.py
from django.shortcuts import render, HttpResponseRedirect
from apps.perfiles.models import Perfil
from apps.roles.models import Rol
# Create your views here.

def inicio(request):
    usuario = request.user.id
    perfil = Perfil.objects.get(user_id=usuario)
    roles = perfil.roles.all()
    privi = []
    privilegios = []
    privilegio = []
    for r in roles:
        privi.append(r.id)
    for p in privi:
        roles5 = Rol.objects.get(pk=p)
        priv = roles5.privilegios.all()
        for pr in priv:
            privilegios.append(pr.codename)
    for i in privilegios:
        if i not in privilegio:
            privilegio.append(i)

    return render(request, 'base1/inicio.html', {'usuario': privilegio})

Cienciometrico/templates/base1/inicio.html
{% load staticfiles %}

<!DOCTYPE html>
<style>
footer {
    padding: 1em;
    color: white;
    background: #009688;
    clear: left;
    text-align: center;
}

</style>
<html>
	<title>{% block title %}Cienciometrico {% endblock %}</title>
	{% block extrastatic %}
	{% endblock %}
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<link rel="stylesheet" href="{% static 'css/inputTags.css' %}">

     <script type="text/javascript" src="{% static 'js/inputTags.jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/app.js' %}"></script>

     {% include 'material/includes/material_css.html' %}
    <script src="{% static 'material/js/jquery.js' %}"></script>
    {% include 'material/includes/material_js.html' %}
<head><script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
       <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script>
    $(document).ready(function(){
    $('.datepicker').pickadate({
    selectMonths: false, // Creates a dropdown to control month
    selectYears: 15,
    today: 'Today',
    format:'dd/mm/yyyy',
    clear: 'Clear',
    close: 'Ok',
    closeOnSelect: false // Close upon selecting a date,
  });
  });
    </script>


    <script>
     $(document).ready( function () {
      $(':input[type=text]').on("keypress", function () {
       $input=$(this);
       setTimeout(function () {
        $input.val($input.val().toUpperCase());
       });
      })
     })
    </script>
    <style>
		#uno {
		background-color: #009688 !important;
		}
	</style>

	<body onload="codeLatLng()" >

		{% block navbar %}
		<div class="w3-sidebar w3-bar-block w3-collapse w3-card w3-animate-left" style="width:200px; background:#E7F1F0; " id="mySidebar">
			<button class="w3-bar-item w3-button w3-large w3-hide-large" onclick="w3_close()">Close &times;</button>
             {% block home %}
    <a href="{% url 'inicio:logeo' %}" id="uno" class=" w3-bar-item w3-button"><img width="15%" src="{% static 'images/home.png' %}"> Home</a>
    {% endblock %}
            {% if user.is_authenticated and user.is_staff == True and user.is_superuser == True %}

            <label>Datos Generales</label>
            <hr style="margin-top: 0.5em; margin-bottom: 0.5em; margin-left: auto;   margin-right: auto; border-style: inset;   border-width: 1px;">
            {% block pais %}
			<a href="{% url 'pais:pais_listar' %}" class=" w3-bar-item w3-button"><img width="15%" src="{% static 'images/globe.png' %}"> País</a>
			{% endblock %}
            {% block zona %}
            <a href="{% url 'zona:zona_listar' %}" class="w3-bar-item w3-button"><img width="15%" src="{% static 'images/iconos-zona.png' %}"> Zona</a>
			{% endblock %}
            {% block provincia %}
            <a href="{% url 'provincia:provincia_listar' %}"class="w3-bar-item w3-button"><img width="15%" src="{% static 'images/country.png' %}"> Provincia</a>
			{% endblock %}

            {% block canton %}
            <a href="{% url 'canton:canton_listar' %}" class="w3-bar-item w3-button"><img width="15%" src="{% static 'images/city.png' %}"> Cantón</a>
			{% endblock %}

            {% block universidad %}
            <a href="{% url 'universidad:universidad_listar' %}" class="w3-bar-item w3-button"><img width="15%" src="{% static 'images/university.png' %}"> Universidad</a>
			{% endblock %}
            {% endif %}
            {% for us in usuario%}

            {% if us == 'ver_campus' %}
            {% block campus %}
            <a href="{% url 'campus:campus_listar' %}" class="w3-bar-item w3-button"> <img width="15%" src="{% static 'images/campus.png' %}"> Campus</a>
			{% endblock %}
            {% endif %}
            {% if us == 'ver_facultad' %}
            {% block Facultad %}
            <a href="{% url 'Facultad:lista_Facultad' %}"  class="w3-bar-item w3-button"> <img width="15%" src="{% static 'images/facultad5.png' %}"> Facultad</a>
			{% endblock %}
            {% endif %}
            {% endfor%}
            {% for us in usuario%}
            {% if us == 'ver_carrera' %}
            {% block carrera %}
            <a href="{% url 'carrera:lista_Carrera' %}"  class="w3-bar-item w3-button"> <img width="15%" src="{% static 'images/carrera.png' %}"> Carrera</a>
			{% endblock %}

            {% endif %}
            {% endfor%}
            {% if user.is_authenticated and user.is_staff == True and user.is_superuser == True %}
            {% block itemRevista %}
            <a href="{% url 'Revista:lista_Revista' %}" class="w3-bar-item w3-button"><img width="15%" src="{% static 'images/revista.png' %}">Revista</a>
            {% endblock %}
            {% endif%}
            {% if user.is_authenticated and user.is_staff == True and user.is_superuser == True %}
            <label>Usuario</label>
            <hr style="margin-top: 0.5em; margin-bottom: 0.5em; margin-left: auto;   margin-right: auto; border-style: inset;   border-width: 1px;">
            {% block rol %}
            <a href="{% url 'roles:crear_rol' %}"  class=" w3-bar-item w3-button"><img width="15%" src="{% static 'images/roles.png' %}"> Rol</a>
	        {% endblock %}


            {% block usuario %}
                <a href="{% url 'usuario:registrar' %}" class=" w3-bar-item w3-button"><img width="15%" src="{% static 'images/User.png' %}"> Usuario</a>
            {% endblock %}
            {% endif %}

            {% for us in usuario%}
            {% if us == 'ver_datosprofesionales' %}
            <label>Datos Usuario</label>
            <hr style="margin-top: 0.5em; margin-bottom: 0.5em; margin-left: auto;   margin-right: auto; border-style: inset;   border-width: 1px;">
			{% block item5 %}
            <a href="{% url 'datosprofe:datosprofe_listar' %}"  class=" w3-bar-item w3-button"><img width="15%" src="{% static 'images/globe.png' %}"> Datos Profesionales</a>
            {% endblock %}
            {% endif %}
            {% if us == 'ver_formacionAcademica' %}
            {% block itemForAcad %}
            <a href="{% url 'FormacionAcademica:lista_Formacion_Academica' %}" class="w3-bar-item w3-button"><img width="15%" src="{% static 'images/FormaAcad.png' %}">Formación Académica</a>
            {% endblock %}
            {% endif %}
            {% if us == 'ver_FormacionComplementaria' %}
            {% block itemForCompl %}
            <a href="{% url 'FormacionComplementaria:lista_Formacion_Complementaria' %}" class="w3-bar-item w3-button"><img width="15%" src="{% static 'images/FormaComp.png' %}">Formación Complementaria</a>
            {% endblock %}
            {% endif %}
            {% endfor %}
            {% for us in usuario%}
            {% if us == 'ver_articulo' %}
            <label>Producción Científica</label>
            <hr style="margin-top: 0.5em; margin-bottom: 0.5em; margin-left: auto;   margin-right: auto; border-style: inset;   border-width: 1px;">
            {% block itemArti %}
            <a href="{% url 'articulosCientificos:ListaArticulo' %}" class="w3-bar-item w3-button"><img width="15%" src="{% static 'images/articuloCient.png' %}">Artículos Científicos</a>
            {% endblock %}
            {% endif %}
            {% if us == 'ver_libro' %}
            {% block itemLibro %}
            <a href="{% url 'Libro:libro_lis' %}" class="w3-bar-item w3-button"><img width="15%" src="{% static 'images/libro.png' %}">Libros</a>
            {% endblock %}
            {% endif %}
            {% if us == 'ver_ParticipacionesEventos' %}
            {% block item2 %}
            <a href="{% url 'partevento:partevento_lis' %}"class="w3-bar-item w3-button"><img width="15%" src="{% static 'images/country.png' %}"> Participación en Eventos</a>
            {% endblock %}
            {% endif %}
            {% endfor %}
            {% for us in usuario%}
            {% if us == 'ver_Proyectos' %}
            <label>Producción Científica</label>
            <hr style="margin-top: 0.5em; margin-bottom: 0.5em; margin-left: auto;   margin-right: auto; border-style: inset;   border-width: 1px;">
            {% block itemProyecto %}
            <a href="{% url 'proyecto:proyectos_lis' %}" class="w3-bar-item w3-button"><img width="15%" src="{% static 'images/project.png' %}">Proyectos</a>
            {% endblock %}
            {% endif %}
            {% endfor %}
            {% for us in usuario%}
            {% if us == 'ver_otrasinvestigaciones' %}
            {% block item1 %}
            <a href="{% url 'otrainvestigacion:otrasinvestigaciones_lis' %}" class="w3-bar-item w3-button"><img width="15%" src="{% static 'images/iconos-zona.png' %}"> Otras Investigaciones</a>
            {% endblock %}
            {% endif %}
            {% if us == 'ver_Publicaciones' %}
            {% block itemPublicaciones %}
            <a href="{% url 'publicaciones:lista_Publicaciones' %}" class="w3-bar-item w3-button"><img width="15%" src="{% static 'images/publicaciones.png' %}">Otras Publicaciones</a>
            {% endblock %}
            {% endif %}
            {% endfor %}
            {% for us in usuario%}
            {% if us == 'ver_investigaciones' %}

            {% block item %}
            <a href="{% url 'investigacion:investigaciones_lis' %}" class=" w3-bar-item w3-button"><img width="15%" src="{% static 'images/globe.png' %}"> Investigaciones</a>
            {% endblock %}
            {% endif %}

            {% if us == 'ver_evento' %}
            {% block eveto %}
            <a href="{% url 'evento:lista_Evento' %}"  class="w3-bar-item w3-button"> <img width="15%" src="{% static 'images/evento.png' %}">Evento</a>
			{% endblock %}
            {% endif %}










            {% endfor %}

		</div>
		<div class="w3-main" style="margin-left:200px; ">
			<div class="w3-teal"  >
				<button class="w3-button w3-teal w3-xlarge w3-hide-large"  onclick="w3_open()">&#9776;</button>
			</div>
			{% endblock %}
			{% block content %}
            <div class="wow fadeInUp animated" style="background: #009688; height:20%;  padding: 1cm 3cm 1cm 3cm;" >
        <div style="float:right;">
            <strong style="color:white;font-size:100%">Bienvenido/</strong>
            <strong style="color:white;font-size:100%">{{user.username}}/</strong>
            <strong style="color:white;font-size:100%"><a href="{% url 'logout'%}" style="color:white;"><span class="glyphicon glyphicon-log-out"></span>Cerrar Sesion</a></strong>
        </a>
            </div>
    </div>

			<div class="w3-container">
				 <div align="middle" style="margin:17% auto;"><img  src="{% static 'images/logo.png' %}" alt="" ></div>
			</div>

            <footer>Copyright 2018 &copy; </footer>
		</div>
		{% endblock %}
		<script>
			function w3_open() {
			    document.getElementById("mySidebar").style.display = "block";
			}
			function w3_close() {
			    document.getElementById("mySidebar").style.display = "none";
			}
		</script>

     <style>
         #uno {
    background-color: #009688 !important;
    }
    </style>


	</body>
</html>