Cienciometrico/Cienciometrico/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import login, logout_then_login,password_reset,password_reset_done,password_reset_confirm,password_reset_complete
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.principal.urls', namespace="iniciop")),
    url(r'^pais/', include('apps.pais.urls', namespace="pais")),
    url(r'^zona/', include('apps.zona.urls', namespace="zona")),
    url(r'^provincia/', include('apps.provincia.urls', namespace="provincia")),
    url(r'^canton/', include('apps.canton.urls', namespace="canton")),
    url(r'^universidad/', include('apps.universidad.urls', namespace="universidad")),
    url(r'^Carrera/', include('apps.carrera.urls', namespace="carrera")),
    url(r'^Facultad/', include('apps.facultad.urls', namespace="Facultad")),
    url(r'^campus/', include('apps.campus.urls', namespace="campus")),
    url(r'^investigador/', include('apps.Investigador.urls', namespace="investigador")),
    url(r'^articulo/', include('apps.Articulos_Cientificos.urls', namespace="articulosCientificos")),
    url(r'^investigacion/', include('apps.investigaciones.urls', namespace="investigacion")),
    url(r'^datosprofesionales/', include('apps.datosprofesionales.urls', namespace="datosprofe")),
    url(r'^formacionAcad/', include('apps.Formacion_Academica.urls', namespace="FormacionAcademica")),
    url(r'^formacionComple/', include('apps.Formacion_Complementaria.urls', namespace="FormacionComplementaria")),
    url(r'^Evento/', include('apps.Evento.urls', namespace="evento")),
    url(r'^otrainvestigacion/', include('apps.otrasinvestigaciones.urls', namespace="otrainvestigacion")),
    url(r'^participacioneventos/', include('apps.participacioneventos.urls', namespace="partevento")),
    url(r'^proyectos/', include('apps.Proyectos.urls', namespace="proyecto")),
    url(r'^perfiles/', include('apps.perfiles.urls', namespace="usuario")),
    url(r'^roles/', include('apps.roles.urls', namespace="roles")),
    url(r'^login/', include('apps.inicio.urls', namespace="inicio")),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^accounts/login', login,{'template_name':'login.html'},name='login'),
    url(r'^logout/', logout_then_login,  name='logout'),
    url(r'^libro/', include('apps.Libro.urls', namespace="Libro")),
    url(r'^revista/', include('apps.Revista.urls', namespace="Revista")),
    url(r'^Publicaciones/', include('apps.Publicaciones.urls', namespace="publicaciones")),
    #///////////////////////PASSWORD RESET///////////////////////////////////////
    url(r'^password_reset/', password_reset,
       {'template_name': 'registration/password_reset_form.html',
   'email_template_name': 'registration/password_reset_email.html'},
     name='password_reset'),
    url(r'^password_reset_done/', password_reset_done,
       {'template_name': 'registration/password_reset_done.html'},
        name='password_reset_listo'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
        {'template_name': 'registration/password_reset_confirm.html'},
        name='password_reset_confirm'
        ),
    url(r'^done', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},
        name='password_reset_completado'),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Cienciometrico/apps/inicio/urls.py
from apps.inicio.views import inicio
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
urlpatterns = [

    url(r'^inicio$',login_required(inicio), name="logeo"),
    ]

Cienciometrico/apps/otrasinvestigaciones/urls.py
from django.conf.urls import url
from apps.otrasinvestigaciones.models import otrasinvestigaciones
from apps.otrasinvestigaciones.views import Otrainvestigacioncrear,OtrainvestigacionDelete,OtrainvestigacionEdit,OtrainvestigacionList
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^uploads/form/$', login_required(Otrainvestigacioncrear), name='otrasinvestigaciones_crear'),
    url(r'^listar', login_required(OtrainvestigacionList.as_view(queryset= otrasinvestigaciones.objects.all().order_by('id'))), name='otrasinvestigaciones_lis'),
    url(r'^editar/(?P<id_otrainvestigacion>\d+)/$',login_required(OtrainvestigacionEdit), name='otrasinvestigaciones_update'),
    url(r'^eliminar/(?P<pk>\d+)/$',login_required(OtrainvestigacionDelete.as_view()), name='otrasinvestigaciones_eliminar'),
]

Cienciometrico/apps/otrasinvestigaciones/models.py
from django.db import models

# Create your models here.
class otrasinvestigaciones(models.Model):

 Titulo = models.CharField(max_length=255)
 Resumen = models.TextField()
 Palabras_Clave = models.TextField()
 Documento = models.FileField(upload_to='otrasinvestigaciones/', null=True, blank=True)
 uploaded_at = models.DateTimeField(auto_now_add=True)
 FechaInicio = models.DateField()
 FechaFin= models.DateField()
 Url = models.URLField(null=True)

 def __str__(self):
  return '{}'.format(self.Titulo)

 class Meta:
  permissions = (
   ("ver_otrasinvestigaciones", "ver otrasinvesitgaciones"),
  )

Cienciometrico/apps/otrasinvestigaciones/views.py
from django.shortcuts import render,redirect
from django.core.urlresolvers import reverse_lazy
from apps.otrasinvestigaciones.models import otrasinvestigaciones
from django.views.generic import ListView,DeleteView
from apps.otrasinvestigaciones.form import DocumentForm
from apps.roles.models import Rol
from apps.perfiles.models import Perfil
# Create your views here.
def Otrainvestigacioncrear(request):
    usuario = request.user.id
    perfil = Perfil.objects.get(user_id=usuario)
    roles = perfil.roles.all()
    privi = []
    privilegios = []
    privilegio = []
    for r in roles:
        privi.append(r.id)
    for p in privi:
        roles5 = Rol.objects.get(pk=p)
        priv = roles5.privilegios.all()
        for pr in priv:
            privilegios.append(pr.codename)
    for i in privilegios:
        if i not in privilegio:
            privilegio.append(i)
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('otrainvestigacion:otrasinvestigaciones_lis')
    else:
        form = DocumentForm()
    return render(request, 'otrasinvestigaciones/otrasinvestigaciones_crear.html', {
        'form': form, 'usuario': privilegio
    })
class OtrainvestigacionList(ListView):
    model = otrasinvestigaciones
    template_name = 'otrasinvestigaciones/otrasinvestigaciones_listar.html'
    paginate_by = 6
    def get_context_data(self, **kwargs):
        context = super(OtrainvestigacionList, self).get_context_data(**kwargs)
        usuario = self.request.user.id
        perfil = Perfil.objects.get(user_id=usuario)
        roles = perfil.roles.all()
        privi = []
        privilegios = []
        privilegio = []
        for r in roles:
            privi.append(r.id)
        for p in privi:
            roles5 = Rol.objects.get(pk=p)
            priv = roles5.privilegios.all()
            for pr in priv:
                privilegios.append(pr.codename)
        for i in privilegios:
            if i not in privilegio:
                privilegio.append(i)
        context['usuario'] = privilegio
        return context
def OtrainvestigacionEdit(request, id_otrainvestigacion):
    usuario = request.user.id
    perfil = Perfil.objects.get(user_id=usuario)
    roles = perfil.roles.all()
    privi = []
    privilegios = []
    privilegio = []
    for r in roles:
        privi.append(r.id)
    for p in privi:
        roles5 = Rol.objects.get(pk=p)
        priv = roles5.privilegios.all()
        for pr in priv:
            privilegios.append(pr.codename)
    for i in privilegios:
        if i not in privilegio:
            privilegio.append(i)
    oinves = otrasinvestigaciones.objects.get(id=id_otrainvestigacion)
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES,instance=oinves)
        if form.is_valid():
            form.save()
            return redirect('otrainvestigacion:otrasinvestigaciones_lis')
    else:
        form = DocumentForm(instance=oinves)
    return render(request, 'otrasinvestigaciones/otrasinvestigaciones_update.html', {'form': form,'usuario': privilegio})
class OtrainvestigacionDelete(DeleteView):
    model = otrasinvestigaciones
    template_name = 'otrasinvestigaciones/otrasinvestigaciones_delete.html'
    success_url = reverse_lazy('otrainvestigacion:otrasinvestigaciones_lis')
    def get_context_data(self, **kwargs):
        context = super(OtrainvestigacionDelete, self).get_context_data(**kwargs)
        usuario = self.request.user.id
        perfil = Perfil.objects.get(user_id=usuario)
        roles = perfil.roles.all()
        privi = []
        privilegios = []
        privilegio = []
        for r in roles:
            privi.append(r.id)
        for p in privi:
            roles5 = Rol.objects.get(pk=p)
            priv = roles5.privilegios.all()
            for pr in priv:
                privilegios.append(pr.codename)
        for i in privilegios:
            if i not in privilegio:
                privilegio.append(i)
        context['usuario'] = privilegio
        return context

Cienciometrico/templates/otrasinvestigaciones/otrasinvestigaciones_crear.html
{% extends 'base1/inicio.html'%}
{% load staticfiles %}
{% load bootstrap %}
{% load material_form %}
{% load widget_tweaks %}
{% block extrastatic %}
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
   <link rel="stylesheet" href="static/css/animate.min.css">
{% endblock %}
    {% block home %}
    <a href="{% url 'inicio:logeo' %}"  class=" w3-bar-item w3-button"><img width="15%" src="{% static 'images/home.png' %}"> Home</a>
    {% endblock %}
    {% block item1 %}
    <a href="{% url 'otrainvestigacion:otrasinvestigaciones_lis' %}" id="uno" class="w3-bar-item w3-button"><img width="15%" src="{% static 'images/iconos-zona.png' %}"> Otras Investigaciones</a>
    {% endblock %}
{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="wow fadeInUp animated" style="background: #009688; height:20%;  padding: 1cm 3cm 1cm 3cm;" >
     <h4 align="center" style="color:white"><span class="glyphicon glyphicon-plus"></span> NUEVA <span style="color:#FC9C30">OTRA INVESTIGACIÓN</span> </h4>
       <h6><div style="float:right;">
            <strong style="color:white;font-size:100%">Bienvenido/</strong>
            <strong style="color:white;font-size:100%">{{user.username}}/</strong>
            <strong style="color:white;font-size:100%"><a href="{% url 'logout'%}" style="color:white;"><span class="glyphicon glyphicon-log-out"></span>Cerrar Sesión</a></strong>
        </a>
            </div></h6>
        </div>
    <br>
	<div class="container">
		<div class="col-md-10 col-md-offset-2">
	<a href="{% url 'otrainvestigacion:otrasinvestigaciones_lis' %}" class="btn btn-primary  pull-right"><i class="glyphicon glyphicon-eye-open"></i> Ver Todos</a>
		</div>
		</div>
    <div class="row">
		<div class="col-md-8 col-md-offset-2">
            {% form form=form %}{% endform %}
        </div>
    </div>
    <div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<button class="btn btn-primary "type="submit">Guardar</button>
			</div>
		</div>
	</div>
  </form>


{% endblock %}

Cienciometrico/templates/otrasinvestigaciones/otrasinvestigaciones_delete.html
{% extends 'base1/inicio.html'%}
{% load staticfiles %}
    {% block home %}
    <a href="{% url 'inicio:logeo' %}"  class=" w3-bar-item w3-button"><img width="15%" src="{% static 'images/home.png' %}"> Home</a>
    {% endblock %}
    {% block item1 %}
    <a href="{% url 'otrainvestigacion:otrasinvestigaciones_lis' %}" id="uno" class="w3-bar-item w3-button"><img width="15%" src="{% static 'images/iconos-zona.png' %}"> Otras Investigaciones</a>
    {% endblock %}
{% block content %}
<form method="post">
    {% csrf_token %}
    <br><br>
    <h4>¿Desea eliminar el registro de {{object.Titulo}} ?</h4>
    <button class="btn btn-danger" type="submit">Si, eliminar</button>
    <a class="btn btn-default" href="{% url 'otrainvestigacion:otrasinvestigaciones_lis' %}">Cancelar</a>
</form>
{% endblock %}

Cienciometrico/templates/otrasinvestigaciones/otrasinvestigaciones_listar.html
{% extends 'base1/inicio.html'%}
{% load staticfiles %}
{% block extrastatic %}
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
   <link rel="stylesheet" href="static/css/animate.min.css">
{% endblock %}
    {% block home %}
    <a href="{% url 'inicio:logeo' %}"  class=" w3-bar-item w3-button"><img width="15%" src="{% static 'images/home.png' %}"> Home</a>
    {% endblock %}
    {% block item1 %}
    <a href="{% url 'otrainvestigacion:otrasinvestigaciones_lis' %}" id="uno" class="w3-bar-item w3-button"><img width="15%" src="{% static 'images/iconos-zona.png' %}"> Otras Investigaciones</a>
    {% endblock %}
{% block content %}
<div class="wow fadeInUp animated" style="background: #009688; height:20%;  padding: 1cm 3cm 1cm 3cm;" >
     <h4 align="center" style="color:white"><span class="glyphicon glyphicon-th-list"></span> LISTADO DE <span style="color:#FC9C30">OTRAS INVESTIGACIONES</span> </h4>
 <h6><div style="float:right;">
            <strong style="color:white;font-size:100%">Bienvenido/</strong>
            <strong style="color:white;font-size:100%">{{user.username}}/</strong>
            <strong style="color:white;font-size:100%"><a href="{% url 'logout'%}" style="color:white;"><span class="glyphicon glyphicon-log-out"></span>Cerrar Sesión</a></strong>
        </a>
            </div></h6>
</div>
    <br>
<div class="container">
<a href="{% url 'otrainvestigacion:otrasinvestigaciones_crear' %}" class="btn btn-primary  pull-right "><i class="glyphicon glyphicon-plus"></i> Nueva Otra Investigación</a>
    </div>
<br>
<div class="table-responsive">
<table class="table table-bordered" style="text-align:center; width:100%; ">

	<thead >
		<tr>
			<td>#</td>
			<td>Título</td>
			<td>Resumen</td>
			<td>Palabras Claves</td>
            <td>Documento</td>
			<td>Fecha de Inicio</td>
			<td>Fecha de Culminación</td>
            <td>Link</td>
            <td>Acciones</td>
		</tr>

	</thead>
	<tbody>
        {% if object_list %}
        {% for otrasinvestigaciones in object_list %}
        <tr>
            <td>{{otrasinvestigaciones.id}}</td>
            <td>{{otrasinvestigaciones.Titulo}}</td>

            <td>{{otrasinvestigaciones.Resumen}}</td>
            <td>{{otrasinvestigaciones.Palabras_Clave}}</td>
            <td>
                <li>
                    <a href="{{ otrasinvestigaciones.Documento.url }}">{{ otrasinvestigaciones.Documento.name }}</a>
                    <small>(Uploaded at: {{ otrasinvestigaciones.uploaded_at }})</small>
                </li>
            </td>
            <td>{{otrasinvestigaciones.FechaInicio}}</td>
             <td>{{otrasinvestigaciones.FechaFin}}</td>
            <td>{{otrasinvestigaciones.Url}}</td>
            <td>
                <a class="btn btn-warning" href="{% url 'otrainvestigacion:otrasinvestigaciones_update' otrasinvestigaciones.id %}" ><span class="glyphicon glyphicon-pencil"></span> Editar</a>
                <a class="btn btn-danger" href="{% url 'otrainvestigacion:otrasinvestigaciones_eliminar' otrasinvestigaciones.id %}"><span class="glyphicon glyphicon-trash"></span> Eliminar</a>

            </td>
        </tr>
        {% endfor %}

        {% else %}
        <h4>No hay registros de Otras Investigaciones</h4>
        {% endif %}

	</tbody>
</table>

</div>
{% endblock%}

Cienciometrico/templates/otrasinvestigaciones/otrasinvestigaciones_update.html
{% extends 'base1/inicio.html'%}
{% load staticfiles %}
{% load bootstrap %}
{% load material_form %}
{% load widget_tweaks %}
{% block extrastatic %}
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
   <link rel="stylesheet" href="static/css/animate.min.css">
{% endblock %}
    {% block home %}
    <a href="{% url 'inicio:logeo' %}"  class=" w3-bar-item w3-button"><img width="15%" src="{% static 'images/home.png' %}"> Home</a>
    {% endblock %}
    {% block item1 %}
    <a href="{% url 'otrainvestigacion:otrasinvestigaciones_lis' %}" id="uno" class="w3-bar-item w3-button"><img width="15%" src="{% static 'images/iconos-zona.png' %}"> Otras Investigaciones</a>
    {% endblock %}
{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="wow fadeInUp animated" style="background: #009688; height:20%;  padding: 1cm 3cm 1cm 3cm;" >
     <h4 align="center" style="color:white"><span class="glyphicon glyphicon-plus"></span> ACTUALIZAR <span style="color:#FC9C30">OTRA INVESTIGACIÓN</span> </h4>
        <h6><div style="float:right;">
            <strong style="color:white;font-size:100%">Bienvenido/</strong>
            <strong style="color:white;font-size:100%">{{user.username}}/</strong>
            <strong style="color:white;font-size:100%"><a href="{% url 'logout'%}" style="color:white;"><span class="glyphicon glyphicon-log-out"></span>Cerrar Sesión</a></strong>
        </a>
            </div></h6>
        </div>
    <br>
<div class="container">
		<div class="col-md-10 col-md-offset-2">
	<a href="{% url 'otrainvestigacion:otrasinvestigaciones_lis' %}" class="btn btn-primary  pull-right"><i class="glyphicon glyphicon-eye-open"></i> Ver Todos</a>
		</div>
		</div>
    <div class="row">
		<div class="col-md-8 col-md-offset-2">
            {% form form=form %}{% endform %}
        </div>
    </div>
    <div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<button class="btn btn-primary "type="submit">Guardar</button>
                <a href="{% url 'otrainvestigacion:otrasinvestigaciones_lis' %}" class="btn btn-danger"type="button">Cancelar</a>
			</div>
		</div>
	</div>
  </form>


{% endblock %}