Cienciometrico/Cienciometrico/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import login, logout_then_login,password_reset,password_reset_done,password_reset_confirm,password_reset_complete
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.principal.urls', namespace="iniciop")),
    url(r'^pais/', include('apps.pais.urls', namespace="pais")),
    url(r'^zona/', include('apps.zona.urls', namespace="zona")),
    url(r'^provincia/', include('apps.provincia.urls', namespace="provincia")),
    url(r'^canton/', include('apps.canton.urls', namespace="canton")),
    url(r'^universidad/', include('apps.universidad.urls', namespace="universidad")),
    url(r'^Carrera/', include('apps.carrera.urls', namespace="carrera")),
    url(r'^Facultad/', include('apps.facultad.urls', namespace="Facultad")),
    url(r'^campus/', include('apps.campus.urls', namespace="campus")),
    url(r'^investigador/', include('apps.Investigador.urls', namespace="investigador")),
    url(r'^articulo/', include('apps.Articulos_Cientificos.urls', namespace="articulosCientificos")),
    url(r'^investigacion/', include('apps.investigaciones.urls', namespace="investigacion")),
    url(r'^datosprofesionales/', include('apps.datosprofesionales.urls', namespace="datosprofe")),
    url(r'^formacionAcad/', include('apps.Formacion_Academica.urls', namespace="FormacionAcademica")),
    url(r'^formacionComple/', include('apps.Formacion_Complementaria.urls', namespace="FormacionComplementaria")),
    url(r'^Evento/', include('apps.Evento.urls', namespace="evento")),
    url(r'^otrainvestigacion/', include('apps.otrasinvestigaciones.urls', namespace="otrainvestigacion")),
    url(r'^participacioneventos/', include('apps.participacioneventos.urls', namespace="partevento")),
    url(r'^proyectos/', include('apps.Proyectos.urls', namespace="proyecto")),
    url(r'^perfiles/', include('apps.perfiles.urls', namespace="usuario")),
    url(r'^roles/', include('apps.roles.urls', namespace="roles")),
    url(r'^login/', include('apps.inicio.urls', namespace="inicio")),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^accounts/login', login,{'template_name':'login.html'},name='login'),
    url(r'^logout/', logout_then_login,  name='logout'),
    url(r'^libro/', include('apps.Libro.urls', namespace="Libro")),
    url(r'^revista/', include('apps.Revista.urls', namespace="Revista")),
    url(r'^Publicaciones/', include('apps.Publicaciones.urls', namespace="publicaciones")),
    #///////////////////////PASSWORD RESET///////////////////////////////////////
    url(r'^password_reset/', password_reset,
       {'template_name': 'registration/password_reset_form.html',
   'email_template_name': 'registration/password_reset_email.html'},
     name='password_reset'),
    url(r'^password_reset_done/', password_reset_done,
       {'template_name': 'registration/password_reset_done.html'},
        name='password_reset_listo'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
        {'template_name': 'registration/password_reset_confirm.html'},
        name='password_reset_confirm'
        ),
    url(r'^done', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},
        name='password_reset_completado'),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Cienciometrico/apps/Proyectos/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from apps.Proyectos.models import proyecto
from apps.Proyectos.views import Proyectocrear,ProyectoDelete,ProyectoEdit,ProyectoList
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^uploads/form/$', login_required(Proyectocrear), name='proyectos_crear'),
    url(r'^listar', login_required(ProyectoList.as_view(queryset= proyecto.objects.all().order_by('id'))), name='proyectos_lis'),
    url(r'^editar/(?P<id_proyecto>\d+)/$',login_required(ProyectoEdit), name='proyectos_update'),
    url(r'^eliminar/(?P<pk>\d+)/$',login_required(ProyectoDelete.as_view()), name='proyectos_eliminar'),
]

Cienciometrico/apps/inicio/urls.py
from apps.inicio.views import inicio
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
urlpatterns = [

    url(r'^inicio$',login_required(inicio), name="logeo"),
    ]

Cienciometrico/apps/Proyectos/models.py
from django.db import models
from apps.Investigador.models import investigador
# Create your models here.
class proyecto(models.Model):
    Titulo = models.CharField(max_length=255)
    Resumen=models.TextField()
    Palabras_Claves = models.TextField()
    Tipo = models.CharField(max_length=255)
    LineaInvestigacion = models.CharField(max_length=255)
    Documentos = models.FileField(upload_to='proyecto/', null=True, blank=True)
    uploaded_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        permissions = (
            ("ver_Proyectos", "ver Proyectos"),
        )

Cienciometrico/apps/Proyectos/views.py
from django.shortcuts import render,redirect
from django.core.urlresolvers import reverse_lazy
from apps.Proyectos.form import DocumentForm
from apps.Proyectos.models import proyecto
from django.views.generic import ListView,DeleteView
from apps.perfiles.models import Perfil
from apps.roles.models import Rol
# Create your views here.
def Proyectocrear(request):
    usuario = request.user.id
    perfil = Perfil.objects.get(user_id=usuario)
    roles = perfil.roles.all()
    privi = []
    privilegios = []
    privilegio = []
    for r in roles:
        privi.append(r.id)
    for p in privi:
        roles5 = Rol.objects.get(pk=p)
        priv = roles5.privilegios.all()
        for pr in priv:
            privilegios.append(pr.codename)
    for i in privilegios:
        if i not in privilegio:
            privilegio.append(i)
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('proyecto:proyectos_lis')
    else:
        form = DocumentForm()
    return render(request, 'proyecto/proyectos_crear.html', {
        'form': form, 'usuario': privilegio
    })
class ProyectoList(ListView):
    model = proyecto
    template_name = 'proyecto/proyectos_listar.html'
    paginate_by = 6
    def get_context_data(self, **kwargs):
        context = super(ProyectoList, self).get_context_data(**kwargs)
        usuario = self.request.user.id
        perfil = Perfil.objects.get(user_id=usuario)
        roles = perfil.roles.all()
        privi = []
        privilegios = []
        privilegio = []
        for r in roles:
            privi.append(r.id)
        for p in privi:
            roles5 = Rol.objects.get(pk=p)
            priv = roles5.privilegios.all()
            for pr in priv:
                privilegios.append(pr.codename)
        for i in privilegios:
            if i not in privilegio:
                privilegio.append(i)
        context['usuario'] = privilegio
        return context

def ProyectoEdit(request, id_proyecto):
    usuario = request.user.id
    perfil = Perfil.objects.get(user_id=usuario)
    roles = perfil.roles.all()
    privi = []
    privilegios = []
    privilegio = []
    for r in roles:
        privi.append(r.id)
    for p in privi:
        roles5 = Rol.objects.get(pk=p)
        priv = roles5.privilegios.all()
        for pr in priv:
            privilegios.append(pr.codename)
    for i in privilegios:
        if i not in privilegio:
            privilegio.append(i)
    proy = proyecto.objects.get(id=id_proyecto)
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES,instance=proy)
        if form.is_valid():
            form.save()
            return redirect('proyecto:proyectos_lis')
    else:
        form = DocumentForm(instance=proy)
    return render(request, 'proyecto/proyectos_update.html', {'form': form, 'usuario': privilegio})

class ProyectoDelete(DeleteView):
    model = proyecto
    template_name = 'proyecto/proyectos_delete.html'
    success_url = reverse_lazy('proyecto:proyectos_lis')
    def get_context_data(self, **kwargs):
        context = super(ProyectoDelete, self).get_context_data(**kwargs)
        usuario = self.request.user.id
        perfil = Perfil.objects.get(user_id=usuario)
        roles = perfil.roles.all()
        privi = []
        privilegios = []
        privilegio = []
        for r in roles:
            privi.append(r.id)
        for p in privi:
            roles5 = Rol.objects.get(pk=p)
            priv = roles5.privilegios.all()
            for pr in priv:
                privilegios.append(pr.codename)
        for i in privilegios:
            if i not in privilegio:
                privilegio.append(i)
        context['usuario'] = privilegio
        return context

Cienciometrico/templates/proyecto/proyectos_crear.html
{% extends 'base1/inicio.html'%}
{% load staticfiles %}
{% load bootstrap %}
{% load material_form %}
{% load widget_tweaks %}
{% block extrastatic %}
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
   <link rel="stylesheet" href="static/css/animate.min.css">
{% endblock %}
    {% block home %}
    <a href="{% url 'inicio:logeo' %}"  class=" w3-bar-item w3-button"><img width="15%" src="{% static 'images/home.png' %}"> Home</a>
    {% endblock %}
     {% block itemProyecto %}
    <a href="{% url 'proyecto:proyectos_lis' %}" id="uno" class="w3-bar-item w3-button"><img width="15%" src="{% static 'images/project.png' %}">Proyectos</a>
    {% endblock %}
{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="wow fadeInUp animated" style="background: #009688; height:20%;  padding: 1cm 3cm 1cm 3cm;" >
     <h4 align="center" style="color:white"><span class="glyphicon glyphicon-plus"></span> NUEVO <span style="color:#FC9C30">PROYECTO</span> </h4>
     <h6><div style="float:right;">
            <strong style="color:white;font-size:100%">Bienvenido/</strong>
            <strong style="color:white;font-size:100%">{{user.username}}/</strong>
            <strong style="color:white;font-size:100%"><a href="{% url 'logout'%}" style="color:white;"><span class="glyphicon glyphicon-log-out"></span>Cerrar Sesión</a></strong>
        </a>
            </div></h6>
    </div>
    <br>
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
	<a href="{% url 'proyecto:proyectos_lis' %}" class="btn btn-primary  pull-right"><i class="glyphicon glyphicon-eye-open"></i> Ver Todos</a>
</div>
</div>
     <div class="row">
		<div class="col-md-8 col-md-offset-2">

              {% form form=form %}{% endform %}
        </div>
    </div>
      <div class="row">
		<div class="col-md-12 col-md-offset-2">
			<div class="form-group">
				 <button type="submit"   class="btn btn-primary" >Guardar</button>
            </div>
			</div>
		</div>
	</div>
  </form>


{% endblock %}

Cienciometrico/templates/proyecto/proyectos_delete.html
{% extends 'base1/inicio.html'%}
{% load staticfiles %}
    {% block home %}
    <a href="{% url 'inicio:logeo' %}"  class=" w3-bar-item w3-button"><img width="15%" src="{% static 'images/home.png' %}"> Home</a>
    {% endblock %}
     {% block itemProyecto %}
    <a href="{% url 'proyecto:proyectos_lis' %}" id="uno" class="w3-bar-item w3-button"><img width="15%" src="{% static 'images/project.png' %}">Proyectos</a>
    {% endblock %}
{% block content %}
<form method="post">
    {% csrf_token %}
    <br><br>
    <h4>¿Desea eliminar el registro de {{object.Titulo}} ?</h4>
    <button class="btn btn-danger" type="submit">Si, eliminar</button>
    <a class="btn btn-default" href="{% url 'proyecto:proyectos_lis' %}">Cancelar</a>
</form>
{% endblock %}

Cienciometrico/templates/proyecto/proyectos_listar.html
{% extends 'base1/inicio.html'%}
{% load staticfiles %}
{% block extrastatic %}
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
   <link rel="stylesheet" href="static/css/animate.min.css">
{% endblock %}
    {% block home %}
    <a href="{% url 'inicio:logeo' %}"  class=" w3-bar-item w3-button"><img width="15%" src="{% static 'images/home.png' %}"> Home</a>
    {% endblock %}
    {% block itemProyecto %}
    <a href="{% url 'proyecto:proyectos_lis' %}" id="uno" class="w3-bar-item w3-button"><img width="15%" src="{% static 'images/project.png' %}">Proyectos</a>
    {% endblock %}
{% block content %}
<div class="wow fadeInUp animated" style="background: #009688; height:20%;  padding: 1cm 3cm 1cm 3cm;" >
     <h4 align="center" style="color:white"><span class="glyphicon glyphicon-th-list"></span> LISTADO DE <span style="color:#FC9C30">PROYECTOS</span> </h4>
        <h6><div style="float:right;">
            <strong style="color:white;font-size:100%">Bienvenido/</strong>
            <strong style="color:white;font-size:100%">{{user.username}}/</strong>
            <strong style="color:white;font-size:100%"><a href="{% url 'logout'%}" style="color:white;"><span class="glyphicon glyphicon-log-out"></span>Cerrar Sesión</a></strong>
        </a>
            </div></h6>
        </div>
    <br>
<div class="container">
<a href="{% url 'proyecto:proyectos_crear' %}" class="btn btn-primary  pull-right "><i class="glyphicon glyphicon-plus"></i> Nuevo Proyecto</a>
    </div>
<br>
<div class="container" align="center" style="width:90%;">
<table class="table table-bordered" style="text-align:center; ">
	<thead >
		<tr>
			<td>#</td>
			<td>Título</td>
			<td>Resumen</td>
			<td>Palabras Claves</td>
			<td>Tipo</td>
            <td>Lineas de Investigación</td>
            <td>Documento</td>
            <td>Acciones</td>
		</tr>

	</thead>
	<tbody>
        {% if object_list %}
        {% for proyecto in object_list %}
        <tr>
            <td>{{proyecto.id}}</td>
            <td>{{proyecto.Titulo}}</td>
            <td>{{proyecto.Resumen}}</td>
            <td>{{proyecto.Palabras_Claves}}</td>
            <td>{{proyecto.Tipo}}</td>
            <td>{{proyecto.LineaInvestigacion}}</td>
             <td>
                <li>
                    <a href="{{ proyecto.Documentos.url }}">{{ proyecto.Documentos.name }}</a>
                    <small>(Uploaded at: {{ proyecto.uploaded_at }})</small>
                </li>
            </td>
            <td>
                <a class="btn btn-warning" href="{% url 'proyecto:proyectos_update' proyecto.id %}" ><span class="glyphicon glyphicon-pencil"></span> Editar</a>
                <a class="btn btn-danger" href="{% url 'proyecto:proyectos_eliminar' proyecto.id %}"><span class="glyphicon glyphicon-trash"></span> Eliminar</a>

            </td>
        </tr>
        {% endfor %}

        {% else %}
        <h4>No hay registros de Proyectos</h4>
        {% endif %}

	</tbody>
</table>

</div>
{% endblock%}

Cienciometrico/templates/proyecto/proyectos_update.html
{% extends 'base1/inicio.html'%}
{% load staticfiles %}
{% load bootstrap %}
{% load material_form %}
{% load widget_tweaks %}
{% block extrastatic %}
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
   <link rel="stylesheet" href="static/css/animate.min.css">
{% endblock %}
    {% block home %}
    <a href="{% url 'inicio:logeo' %}"  class=" w3-bar-item w3-button"><img width="15%" src="{% static 'images/home.png' %}"> Home</a>
    {% endblock %}
     {% block itemProyecto %}
    <a href="{% url 'proyecto:proyectos_lis' %}" id="uno" class="w3-bar-item w3-button"><img width="15%" src="{% static 'images/project.png' %}">Proyectos</a>
    {% endblock %}
{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="wow fadeInUp animated" style="background: #009688; height:20%;  padding: 1cm 3cm 1cm 3cm;" >
     <h4 align="center" style="color:white"><span class="glyphicon glyphicon-plus"></span> ACTUALIZAR <span style="color:#FC9C30">PROYECTOS</span> </h4>
        <h6><div style="float:right;">
            <strong style="color:white;font-size:100%">Bienvenido/</strong>
            <strong style="color:white;font-size:100%">{{user.username}}/</strong>
            <strong style="color:white;font-size:100%"><a href="{% url 'logout'%}" style="color:white;"><span class="glyphicon glyphicon-log-out"></span>Cerrar Sesión</a></strong>
        </a>
            </div></h6>
        </div>
    <br>

    <div class="row">
		<div class="col-md-8 col-md-offset-2">
           {% form form=form %}{% endform %}
        </div>
    </div>
    <div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<button class="btn btn-primary "type="submit">Guardar</button>
                <a href="{% url 'proyecto:proyectos_lis' %}" class="btn btn-danger"type="button">Cancelar</a>
			</div>
		</div>
	</div>
  </form>


{% endblock %}